name: GPU CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:

  pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0

  build:
    runs-on: self-hosted
    steps:
    - name: Test 
      run: |
        cd ${{ github.workspace }}; ls -l;  tox -e test-gpu

